all: true
include:
  - 'src/'
exclude:
  - 'src/server.js'
  - 'src/service.js'
  - 'src/swapi-rest.js'
clean: true
temp-directory: 'coverage/tests'
report-dir: 'coverage/tests'
skip-full: true
reporter: [json, html, text]
check-coverage: true
